language: go
go_import_path: neugram.io/ng
go:
  - 1.10.x
  - 1.11.x
  - master
os:
  - linux
  - osx
matrix:
 fast_finish: true

script:
  - ./.ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
