language: go
go_import_path: neugram.io/ng
go:
  - 1.9.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: 1.9.x


script:
  - ./.ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
